# Form implementation generated from reading ui file '.\roady.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(578, 388)
        MainWindow.setFixedSize(480, 356)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.departure_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.departure_label.setGeometry(QtCore.QRect(10, 30, 101, 31))
        self.departure_label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.departure_label.setObjectName("departure_label")
        self.departure_city_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.departure_city_lineEdit.setGeometry(QtCore.QRect(150, 30, 111, 31))
        self.departure_city_lineEdit.setObjectName("departure_city_lineEdit")
        self.destination_label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.destination_label_2.setGeometry(QtCore.QRect(10, 80, 101, 31))
        self.destination_label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.destination_label_2.setObjectName("destination_label_2")
        self.destination_city_lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.destination_city_lineEdit_2.setGeometry(QtCore.QRect(150, 80, 111, 31))
        self.destination_city_lineEdit_2.setObjectName("destination_city_lineEdit_2")
        self.return_radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.return_radioButton.setGeometry(QtCore.QRect(150, 140, 71, 31))
        self.return_radioButton.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.return_radioButton.setObjectName("return_radioButton")
        self.one_way_radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.one_way_radioButton_2.setGeometry(QtCore.QRect(10, 140, 81, 31))
        self.one_way_radioButton_2.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.one_way_radioButton_2.setObjectName("one_way_radioButton_2")
        self.currency_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.currency_comboBox.setGeometry(QtCore.QRect(280, 140, 71, 31))
        self.currency_comboBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 85, 255);\n"
"")
        self.currency_comboBox.setObjectName("currency_comboBox")
        self.currency_comboBox.addItem("")
        self.currency_comboBox.addItem("")
        self.currency_comboBox.addItem("")
        self.gas_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.gas_comboBox.setGeometry(QtCore.QRect(10, 300, 101, 31))
        self.gas_comboBox.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.gas_comboBox.setObjectName("gas_comboBox")
        self.gas_comboBox.addItem("")
        self.gas_comboBox.addItem("")
        self.persons_label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.persons_label_3.setGeometry(QtCore.QRect(10, 200, 101, 31))
        self.persons_label_3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.persons_label_3.setObjectName("persons_label_3")
        self.persons_lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.persons_lineEdit_3.setGeometry(QtCore.QRect(150, 200, 111, 31))
        self.persons_lineEdit_3.setObjectName("persons_lineEdit_3")
        self.consumption_label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.consumption_label_5.setGeometry(QtCore.QRect(10, 250, 101, 31))
        self.consumption_label_5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);")
        self.consumption_label_5.setObjectName("consumption_label_5")
        self.consumption_lineEdit_4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.consumption_lineEdit_4.setGeometry(QtCore.QRect(150, 250, 111, 31))
        self.consumption_lineEdit_4.setObjectName("consumption_lineEdit_4")
        self.calculate_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculate_pushButton.setGeometry(QtCore.QRect(280, 300, 81, 31))
        self.calculate_pushButton.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.calculate_pushButton.setObjectName("calculate_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 578, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.departure_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Departure</p></body></html>"))
        self.destination_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Destination</p></body></html>"))
        self.return_radioButton.setText(_translate("MainWindow", "Return"))
        self.one_way_radioButton_2.setText(_translate("MainWindow", "One Way"))
        self.currency_comboBox.setItemText(0, _translate("MainWindow", "RON"))
        self.currency_comboBox.setItemText(1, _translate("MainWindow", "EURO"))
        self.currency_comboBox.setItemText(2, _translate("MainWindow", "GBP"))
        self.gas_comboBox.setItemText(0, _translate("MainWindow", "Gas"))
        self.gas_comboBox.setItemText(1, _translate("MainWindow", "Diesel"))
        self.persons_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Persons</p></body></html>"))
        self.consumption_label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Consumption</p></body></html>"))
        self.calculate_pushButton.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
